# Site settings
title: Cory Lucas DOT Com
email: cory@corylucas.com
author: Cory Lucas
description: "The home page and blog of Cory Lucas, a software engineer and technology leader."
baseurl: ""
url: "http://www.corylucas.com"
bluesky_username: coryflucas
github_username:  coryflucas
version: 1
# Build settings
markdown: kramdown
permalink: pretty
include:
  - .well-known